# Generated by Django 3.0 on 2019-12-11 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_rol', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logyreg.Carreras')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problemas_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.FileField(null=True, upload_to='')),
                ('id_rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logyreg.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=1)),
                ('id_rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logyreg.Usuarios')),
            ],
        ),
    ]
